CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text  NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);


-- INSERT PROJECTS DATA
INSERT INTO projects (name, priority, description, deliverydate)
    VALUES ('make a Web App', 1, 'Using Javascript','2021-05-12')

    INSERT INTO projects (name, priority, description, deliverydate)
        VALUES ('make a Web App 2', 1, 'Using Node','2021-06-12');

-- INSERT TASKS DATA
INSERT INTO task (name, done, projectId)
    VALUES ('Download Vuejs',false, 1);

    INSERT INTO tasks (name, done, projectId)
    VALUES ('Create UI',false, 1);
    
    INSERT INTO tasks (name, done, projectId)
    VALUES ('Download Flutter',false, 2);

    INSERT INTO tasks (name, done, projectId)
    VALUES ('Design UI',false, 2);

